// tilemath.test.js — the SQL in db/0004_tiles.sql is the definition; this
// asserts client/lib/tilemath.js reproduces it exactly. Fixture regenerated by
// tools/tilemath-fixtures.mjs; never edit it by hand.

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

import * as tm from '../lib/tilemath.js';

const fixture = JSON.parse(readFileSync(
    fileURLToPath(new URL('./fixtures/tilemath.json', import.meta.url)), 'utf8'));

test('tiles_for_geom matches SQL for every fixture case', () => {
    assert.equal(fixture.cases.length, 50);
    let rows = 0;
    for (const c of fixture.cases) {
        const got = tm.tilesForGeom(c.geom, c.minZ, c.maxZ).map((t) => [t.z, t.x, t.y]);
        assert.deepEqual(got, c.tiles, `case ${c.i} (${c.kind}, z${c.minZ}..${c.maxZ})`);
        rows += got.length;
    }
    assert.ok(rows > 0, 'fixture carries no tile rows');
});

test('tile_x and tile_y match SQL at every probe', () => {
    for (const p of fixture.probes) {
        assert.equal(tm.tileX(p.lon, p.z), p.x, `x at probe ${p.i}`);
        assert.equal(tm.tileY(p.lat, p.z), p.y, `y at probe ${p.i}`);
    }
});

// West and east are pure arithmetic and must be identical. South and north go
// through atan(sinh(...)), and glibc and V8 disagree there by one ulp — about
// 1e-14 degrees, under a nanometre. Too small to move a tile: tile_x and tile_y
// are compared exactly above, and all 50 tiles_for_geom cases match.
const LIBM_ULP_DEG = 1e-12;

test('tile_bbox matches SQL at every probe', () => {
    for (const p of fixture.probes) {
        const b = tm.tileBbox(p.z, p.x, p.y);
        assert.equal(b.west, p.bbox[0], `west at probe ${p.i}`);
        assert.equal(b.east, p.bbox[2], `east at probe ${p.i}`);
        assert.ok(Math.abs(b.south - p.bbox[1]) < LIBM_ULP_DEG, `south at probe ${p.i}`);
        assert.ok(Math.abs(b.north - p.bbox[3]) < LIBM_ULP_DEG, `north at probe ${p.i}`);
    }
});

test('the ladder is even zooms 6..18', () => {
    assert.deepEqual(tm.ZOOMS, [6, 8, 10, 12, 14, 16, 18]);
    assert.equal(tm.parent(6, 33, 22), null);
    assert.deepEqual(tm.parent(18, 137165, 92795), { z: 16, x: 34291, y: 23198 });
    assert.deepEqual(tm.ancestors(12, 2135, 1442).map((t) => t.z), [10, 8, 6]);
    assert.deepEqual(tm.children(18, 1, 1), []);
});

test('children are the 16 grandchildren, in child_sogs order', () => {
    const kids = tm.children(14, 8543, 5779);
    assert.equal(kids.length, 16);
    assert.deepEqual(kids[0], { z: 16, x: 34172, y: 23116 });
    assert.deepEqual(kids[1], { z: 16, x: 34172, y: 23117 });
    assert.deepEqual(kids[4], { z: 16, x: 34173, y: 23116 });
    for (const k of kids) assert.deepEqual(tm.parent(k.z, k.x, k.y), { z: 14, x: 8543, y: 5779 });
});

test('every tile of a case contains the geometry it came from', () => {
    for (const c of fixture.cases) {
        for (const [z, x, y] of c.tiles) {
            assert.ok(tm.intersectsBbox(c.geom, tm.tileBbox(z, x, y)),
                `case ${c.i}: ${z}/${x}/${y} does not intersect`);
        }
    }
});

test('the local frame is X east, Y up, Z south, and round-trips', () => {
    const o = tm.tileFrame(14, 8543, 5779, 540);
    const east = tm.localFromLonLat(o, o.lon + 0.01, o.lat, 540);
    assert.ok(east.x > 700 && east.x < 800, `east ${east.x}`);
    // Following a parallel is not a straight line in the tangent plane; 764 m
    // east of the origin sits ~5 cm south of it. That curvature is the point of
    // doing this through ECEF rather than a flat-earth scale factor.
    assert.ok(Math.abs(east.z) < 0.1, `east stays on the tangent plane: ${east.z}`);

    const north = tm.localFromLonLat(o, o.lon, o.lat + 0.01, 540);
    assert.ok(north.z < -1000 && north.z > -1200, `north is -Z: ${north.z}`);

    const up = tm.localFromLonLat(o, o.lon, o.lat, 640);
    assert.ok(Math.abs(up.y - 100) < 1e-6, `up ${up.y}`);

    const p = tm.localFromLonLat(o, o.lon + 0.02, o.lat - 0.013, 610);
    const back = tm.lonLatFromLocal(o, p);
    assert.ok(Math.abs(back.lon - (o.lon + 0.02)) < 1e-9, `lon ${back.lon}`);
    assert.ok(Math.abs(back.lat - (o.lat - 0.013)) < 1e-9, `lat ${back.lat}`);
    assert.ok(Math.abs(back.h - 610) < 1e-6, `h ${back.h}`);
});

test('the tile centre is inside its own bbox', () => {
    for (const z of tm.ZOOMS) {
        const c = tm.tileCenter(z, 3, 5);
        assert.equal(tm.tileX(c.lon, z), 3);
        assert.equal(tm.tileY(c.lat, z), 5);
    }
});
