-- 0008_admin.sql — the admin path: schema `gis`, published to GeoServer and
-- edited from QGIS over WFS-T. This is the ONE write path that does not go
-- through row-level security, which is why it is a separate login role with
-- BYPASSRLS rather than a wider policy: Invariant 6 keeps holding for clients.
-- GeoServer stays admin/visualisation only and is never the app API (Inv. 9).

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'geoserver') THEN
        CREATE ROLE geoserver LOGIN BYPASSRLS;
    END IF;
END
$$;
ALTER ROLE geoserver PASSWORD :'geopw';

CREATE SCHEMA gis;
GRANT USAGE ON SCHEMA gis TO geoserver;
GRANT USAGE ON SCHEMA public TO geoserver;
GRANT SELECT, INSERT, UPDATE, DELETE ON feature, instance, area, grant_ TO geoserver;
GRANT SELECT ON tile, job, atom, asset, artifact TO geoserver;

-- One editable layer per feature kind. Auto-updatable views with a column
-- default, so drawing a forest in QGIS inserts kind='forest' by itself.
CREATE VIEW gis.feature_road AS
SELECT * FROM feature WHERE kind = 'road' AND deleted_at IS NULL WITH CHECK OPTION;
CREATE VIEW gis.feature_forest AS
SELECT * FROM feature WHERE kind = 'forest' AND deleted_at IS NULL WITH CHECK OPTION;
CREATE VIEW gis.feature_water AS
SELECT * FROM feature WHERE kind = 'water' AND deleted_at IS NULL WITH CHECK OPTION;
CREATE VIEW gis.feature_footprint AS
SELECT * FROM feature WHERE kind = 'footprint' AND deleted_at IS NULL WITH CHECK OPTION;
CREATE VIEW gis.feature_terrainmod AS
SELECT * FROM feature WHERE kind = 'terrainmod' AND deleted_at IS NULL WITH CHECK OPTION;

ALTER VIEW gis.feature_road ALTER COLUMN kind SET DEFAULT 'road';
ALTER VIEW gis.feature_forest ALTER COLUMN kind SET DEFAULT 'forest';
ALTER VIEW gis.feature_water ALTER COLUMN kind SET DEFAULT 'water';
ALTER VIEW gis.feature_footprint ALTER COLUMN kind SET DEFAULT 'footprint';
ALTER VIEW gis.feature_terrainmod ALTER COLUMN kind SET DEFAULT 'terrainmod';

CREATE VIEW gis.area AS SELECT * FROM area;
CREATE VIEW gis.instance AS SELECT * FROM instance;

-- Read-only overview layer: compile state on the map.
CREATE VIEW gis.tile AS
SELECT
    t.z, t.x, t.y, t.dirty, t.expected_version, t.published_version,
    t.published_at,
    CASE
        WHEN t.published_version = 0 THEN 'unpublished'
        WHEN t.dirty THEN 'stale'
        ELSE 'current'
    END AS status,
    tile_bbox(t.z, t.x, t.y) AS geom
FROM tile t;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA gis TO geoserver;

-- GeoTools finds a layer's identifier through this table when the source is a
-- view rather than a table.
CREATE TABLE gis.gt_pk_metadata (
    table_schema  varchar(32) NOT NULL,
    table_name    varchar(32) NOT NULL,
    pk_column     varchar(32) NOT NULL,
    pk_column_idx integer,
    pk_policy     varchar(32) CHECK (pk_policy IN ('sequence', 'assigned', 'autogenerated')),
    pk_sequence   varchar(64),
    UNIQUE (table_schema, table_name, pk_column)
);
INSERT INTO gis.gt_pk_metadata (table_schema, table_name, pk_column, pk_column_idx, pk_policy)
SELECT 'gis', v, 'id', 0, 'autogenerated'
FROM unnest(ARRAY['feature_road', 'feature_forest', 'feature_water',
                  'feature_footprint', 'feature_terrainmod', 'area', 'instance']) AS v;
GRANT SELECT ON gis.gt_pk_metadata TO geoserver;
