-- 0031_gisviews.sql — what QGIS draws on: views with only the drawable columns.
--
-- GeoServer sends every column of a layer, and fills a blank with a
-- placeholder rather than NULL ('' for text, 0 for a number) — '' into jsonb
-- is refused before any trigger runs. Publishing a subset of a table's columns
-- is not a way out: GeoServer makes such a layer read-only. So the layer is a
-- view with only the columns a drawer touches; everything else is filled in
-- by the table's defaults and triggers (0028, 0030). A view has no primary
-- key of its own, which is what gis.gt_pk_metadata (0008) is for, and the
-- setup now proves the result with a real write.

DROP VIEW gis.area;
CREATE VIEW gis.area AS SELECT id, geom, detail FROM area;

CREATE VIEW gis.feature AS
SELECT id, kind, geom FROM feature WHERE deleted_at IS null WITH CHECK OPTION;

GRANT SELECT, INSERT, UPDATE, DELETE ON gis.area, gis.feature TO geoserver;

INSERT INTO gis.gt_pk_metadata (table_schema, table_name, pk_column, pk_column_idx, pk_policy)
VALUES ('gis', 'feature', 'id', 0, 'autogenerated');
