-- 0041_gisforms.sql — the drawing layers, built from the world's vocabulary.
--
-- TASKS-usable T2 and T3: the form QGIS shows for a wood has to offer the
-- properties an admin defined for a wood, with the values they chose. QGIS
-- learns a layer's fields from the layer, and `feature.props` is one jsonb
-- column, so a layer of woods must publish `leaf_type` as a column of its own.
--
-- The views below are therefore generated from `kind` and `property` rather
-- than written out: defining a property rebuilds them, and QGIS sees a new
-- field the next time it reads the layer. Nothing about the world's shape lives
-- in this file — only the rule that a property becomes a column.

DROP VIEW IF EXISTS gis.feature_road, gis.feature_forest, gis.feature_water,
    gis.feature_footprint, gis.feature_terrainmod CASCADE;

-- Writing back: a column that is a defined property goes into props, the
-- geometry and the area go into their own columns, and anything else is
-- ignored. One trigger for every generated layer; the kind is its argument.
CREATE OR REPLACE FUNCTION gis_kind_write() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE
    k      text := tg_argv[0];
    -- Not `props`: a local of that name is ambiguous against feature.props in
    -- the UPDATE below, which is the same trap db/0009 and db/0014 paid for.
    typed  jsonb := '{}'::jsonb;
    p      record;
    value  text;
    row_id uuid;
BEGIN
    IF tg_op = 'DELETE' THEN
        DELETE FROM feature WHERE feature.id = old.id;
        RETURN old;
    END IF;
    FOR p IN SELECT property.name FROM property WHERE property.kind = k LOOP
        EXECUTE format('SELECT ($1).%I::text', p.name) INTO value USING new;
        IF value IS NOT NULL AND value <> '' THEN
            typed := typed || jsonb_build_object(p.name, value);
        END IF;
    END LOOP;

    IF tg_op = 'INSERT' THEN
        INSERT INTO feature (id, kind, geom, props)
        VALUES (coalesce(new.id, gen_random_uuid()), k, new.geom, typed)
        RETURNING feature.id INTO row_id;
        new.id := row_id;
        RETURN new;
    END IF;
    UPDATE feature SET geom = new.geom, props = typed WHERE feature.id = old.id;
    RETURN new;
END
$$;

-- The geometry a kind is drawn as, in the words PostGIS uses.
CREATE FUNCTION gis_geometry_type(p_geometry text) RETURNS text
LANGUAGE sql IMMUTABLE AS $$
SELECT CASE p_geometry
    WHEN 'line' THEN 'MultiLineString'
    WHEN 'point' THEN 'Point'
    ELSE 'MultiPolygon' END;
$$;

-- One layer per kind that is drawn, with one column per property. Called by the
-- trigger below whenever the vocabulary changes, and once at the end of this
-- migration. Invariant 6 holds: these are views over `feature`, and the
-- geoserver role reaches them with its own grants.
CREATE FUNCTION rebuild_gis_layers() RETURNS int
LANGUAGE plpgsql AS $$
DECLARE
    k       record;
    columns text;
    view    text;
    n       int := 0;
BEGIN
    FOR view IN
        SELECT table_name FROM information_schema.views
        WHERE table_schema = 'gis' AND table_name LIKE 'f_%'
    LOOP
        EXECUTE format('DROP VIEW IF EXISTS gis.%I CASCADE', view);
        DELETE FROM gis.gt_pk_metadata WHERE table_name = view;
    END LOOP;

    FOR k IN SELECT * FROM kind WHERE geometry IS NOT NULL AND applies_to = 'feature'
             ORDER BY ordering, name
    LOOP
        SELECT coalesce(string_agg(
            format('nullif(f.props ->> %L, %L)::%s AS %I',
                   p.name, '',
                   CASE p.type WHEN 'number' THEN 'double precision'
                               WHEN 'boolean' THEN 'boolean' ELSE 'text' END,
                   p.name), ', ' ORDER BY p.ordering, p.name), '')
        INTO columns FROM property p WHERE p.kind = k.name;

        EXECUTE format($view$
            CREATE VIEW gis.%I AS
            SELECT f.id, f.area_id, f.rev%s%s,
                   st_force2d(f.geom)::geometry(%s, 4326) AS geom
            FROM feature f
            WHERE f.kind = %L AND f.deleted_at IS NULL$view$,
            'f_' || k.name,
            CASE WHEN columns = '' THEN '' ELSE ', ' END, columns,
            gis_geometry_type(k.geometry), k.name);

        EXECUTE format(
            'CREATE TRIGGER write INSTEAD OF INSERT OR UPDATE OR DELETE ON gis.%I'
            ' FOR EACH ROW EXECUTE FUNCTION gis_kind_write(%L)',
            'f_' || k.name, k.name);

        EXECUTE format('GRANT SELECT, INSERT, UPDATE, DELETE ON gis.%I TO geoserver',
                       'f_' || k.name);
        INSERT INTO gis.gt_pk_metadata
            (table_schema, table_name, pk_column, pk_column_idx, pk_policy)
        VALUES ('gis', 'f_' || k.name, 'id', 0, 'autogenerated')
        ON CONFLICT (table_schema, table_name, pk_column) DO NOTHING;
        n := n + 1;
    END LOOP;
    RETURN n;
END
$$;

-- A property is defined and the layer that carries it changes shape. This is
-- the one place in the system where a row rebuilds a view, and it is why
-- nothing has to be migrated to add a word to the world's vocabulary.
CREATE FUNCTION vocabulary_changed() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
    PERFORM rebuild_gis_layers();
    RETURN NULL;
END
$$;

CREATE TRIGGER property_layers AFTER INSERT OR UPDATE OR DELETE ON property
FOR EACH STATEMENT EXECUTE FUNCTION vocabulary_changed();
CREATE TRIGGER kind_layers AFTER INSERT OR UPDATE OR DELETE ON kind
FOR EACH STATEMENT EXECUTE FUNCTION vocabulary_changed();

SELECT rebuild_gis_layers();

-- What a QGIS project needs to lay itself out: the layers, their geometry, and
-- the fields with the values a form should offer.
CREATE FUNCTION gis_layers() RETURNS jsonb
LANGUAGE sql STABLE AS $$
SELECT coalesce(jsonb_agg(jsonb_build_object(
    'layer', 'f_' || k.name,
    'kind', k.name,
    'label', coalesce(nullif(k.label, ''), initcap(k.name)),
    'geometry', k.geometry,
    'fields', coalesce((
        SELECT jsonb_agg(jsonb_build_object(
            'name', p.name, 'label', coalesce(nullif(p.label, ''), p.name),
            'type', p.type, 'choices', to_jsonb(p.choices),
            'required', p.required) ORDER BY p.ordering, p.name)
        FROM property p WHERE p.kind = k.name), '[]'::jsonb))
    ORDER BY k.ordering, k.name), '[]'::jsonb)
FROM kind k
WHERE k.geometry IS NOT NULL AND k.applies_to = 'feature';
$$;
GRANT EXECUTE ON FUNCTION gis_layers() TO anon, player, admin;

CREATE FUNCTION api.gis_layers() RETURNS jsonb
LANGUAGE sql STABLE AS $$SELECT public.gis_layers()$$;
GRANT EXECUTE ON FUNCTION api.gis_layers() TO anon, player, admin;
