-- 0055_areawritableagain.sql — undoes db/0054's view, which broke drawing.
--
-- db/0054 replaced gis.area with a view carrying an INSTEAD OF trigger, on the
-- reasoning that area.owner_id is NOT NULL and absent from the view so an
-- insert could not work. That reasoning was wrong: db/0030 and db/0032 put an
-- `area_0_defaults` BEFORE INSERT trigger on the table itself, which fills the
-- id, the owner and a blank detail. Drawing worked. The view was a plain,
-- auto-updatable one and Postgres wrote straight through it.
--
-- An INSTEAD OF trigger takes that away. A view that has one is not
-- auto-updatable, `information_schema.views.is_updatable` says NO, and
-- GeoTools serves it read-only:
--
--     {http://splatworld}area is read-only
--
-- So the view goes back exactly as it was, and the trigger and its function
-- are dropped. Nothing here is new; this is db/0031's view again.

DROP TRIGGER IF EXISTS gis_area_write ON gis.area;
DROP VIEW IF EXISTS gis.area CASCADE;
DROP FUNCTION IF EXISTS gis_area_write();

CREATE VIEW gis.area AS SELECT id, geom, detail FROM area;
GRANT SELECT, INSERT, UPDATE, DELETE ON gis.area TO geoserver;

INSERT INTO gis.gt_pk_metadata
    (table_schema, table_name, pk_column, pk_column_idx, pk_policy)
VALUES ('gis', 'area', 'id', 0, 'autogenerated')
ON CONFLICT (table_schema, table_name, pk_column) DO NOTHING;
