-- 0057_areamultipart.sql — drawing land in QGIS, for the third and last time.
--
-- The symptom is on Water, or Forest, or anything else drawn inside land:
--
--     Konnte Änderungen am Layer Water nicht festschreiben
--     Insert error: Error inserting features
--
-- but the cause is one layer earlier. `area.geom` is geometry(Polygon, 4326)
-- and 0055 restored `gis.area` as a plain view over it, so a Save from QGIS is
-- refused by the typmod:
--
--     Geometry type (MultiPolygon) does not match column type (Polygon)
--
-- QGIS sends a multipolygon of one part for any polygon layer — its editing
-- buffer hands the provider the layer's own type. No land is saved, and every
-- feature drawn afterwards fails with default_area()'s "nothing here belongs
-- to an area yet", which is the error the drawer actually sees.
--
-- This has now been round the loop twice. 0054 fixed it with exactly the shape
-- below; 0055 reverted the lot because GeoServer then called the layer
-- read-only. That was not the trigger's doing — a view with an INSTEAD OF
-- trigger reports is_insertable_into = YES, checked — it was the primary key:
-- GeoServer serves a layer it cannot key read-only, and the key for a view
-- comes from gis.gt_pk_metadata, whose row 0054 did not put back. It is put
-- back here, last, so that whatever else changes this layer cannot lose it.
--
-- The three possible shapes, each tried against Postgres before choosing:
--   * plain view over a Polygon column — refuses a multipolygon (0055, today);
--   * st_multi() expression column, no trigger — "View columns that are not
--     columns of their base relation are not updatable", so not writable at all;
--   * st_multi() expression column with an INSTEAD OF trigger — writable, and
--     takes a multipolygon or a polygon. This one.
--
-- The table keeps geometry(Polygon, 4326): one area is one ring, and what is
-- stored stays exactly what every reader of `area` already expects. The
-- unwrapping happens on the way in, and a genuine two-ring shape is named
-- rather than silently half-saved.

DROP TRIGGER IF EXISTS gis_area_write ON gis.area;
DROP VIEW IF EXISTS gis.area CASCADE;
DROP FUNCTION IF EXISTS gis_area_write();

CREATE VIEW gis.area AS
SELECT id, st_multi(geom)::geometry(MultiPolygon, 4326) AS geom, detail FROM area;

CREATE FUNCTION gis_area_write() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE
    g geometry := new.geom;
BEGIN
    IF tg_op = 'DELETE' THEN
        DELETE FROM area WHERE id = old.id;
        RETURN old;
    END IF;
    IF g IS NOT null AND st_geometrytype(g) = 'ST_MultiPolygon' THEN
        IF st_numgeometries(g) > 1 THEN
            RAISE EXCEPTION 'an area is one ring, and this one has % — draw '
                            'them as separate areas', st_numgeometries(g);
        END IF;
        g := st_geometryn(g, 1);
    END IF;
    IF tg_op = 'INSERT' THEN
        -- Everything else about an area — the owner, the baseline detail — is
        -- filled in by area_0_defaults on the table, where it has been since
        -- 0030. A blank detail arrives from GeoServer as 0 and is passed
        -- through untouched for that trigger to read.
        INSERT INTO area (id, geom, detail)
        VALUES (coalesce(new.id, gen_random_uuid()), g, new.detail)
        RETURNING id INTO new.id;
        RETURN new;
    END IF;
    UPDATE area SET geom = coalesce(g, geom), detail = coalesce(new.detail, detail)
    WHERE id = old.id;
    RETURN new;
END;
$$;

CREATE TRIGGER gis_area_write INSTEAD OF INSERT OR UPDATE OR DELETE ON gis.area
FOR EACH ROW EXECUTE FUNCTION gis_area_write();

-- QGIS reads a view's column defaults to pre-fill its form.
ALTER VIEW gis.area ALTER COLUMN detail SET DEFAULT 14;

GRANT SELECT, INSERT, UPDATE, DELETE ON gis.area TO geoserver;

-- Last, and never to be dropped again: without this row GeoServer cannot key
-- the layer and serves it read-only, which is what got 0054 reverted.
INSERT INTO gis.gt_pk_metadata
    (table_schema, table_name, pk_column, pk_column_idx, pk_policy)
VALUES ('gis', 'area', 'id', 0, 'autogenerated')
ON CONFLICT (table_schema, table_name, pk_column) DO NOTHING;
